apiVersion: v1
kind: Service
metadata:
  name:  vprofile-service
spec:
  type: LoadBalancer
  selector:
    app: vprofile
  ports:
  - protocol: TCP
    port: 80          # This is the port exposed to the outside world
    targetPort: 8081
